config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :recipes do
    member do
      post'like'
    end
  end
  
  resources :users, except: [:new]
  get 'signup', to: 'users#new' 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  get 'pages/about', to: 'pages#about'
  get 'about', to: 'pages#about' 
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :user #this methode create association with user 
    has_many :likes
    validates :title, presence: true, 
                      length: {minimum: 3, maximum: 35}
    
    validates :description, presence: true, 
                            length: {minimum: 10, maximum: 10000}
    
    validates :user_id, presence: true #this will ensure every time the recipe is create the user_id is present
    
    
    #These are Like and dislike methods to count how many likes or dislike a user has received
    def thumbs_up_total 
        self.likes.where(like: true).size
    end
    def thumbs_down_total 
        self.likes.where(like: false).size
    end
    #source: Udemy course

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  #Before filters use the before_action command to arrange for a particular method to be called before the given actions,
  #This before action will restrict the filter to act only :show, :edit, :update, :destroy
  
  before_action :require_user, except: [:index, :show] 
  # This will restrit all action except the index and sow action as it needs a logged in user too perform the other action
  
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # this will require the same user who created the recipes to perform only edit, update and destroy actions 


  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 2)
    #Source: https://www.railstutorial.org/book/updating_and_deleting_users
    #https://hackhands.com/pagination-rails-will_paginate-gem/  
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user #this will ensure that recipe has a user source: video
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
def like
  @recipe = Recipe.find(params[:id])
  like = Like.create(like: params[:like], user: current_user, recipe: @recipe)
  respond_to do |format|
    if like.valid?
      format.html { redirect_to :back, notice: 'Your selection was successful.' }
    else
      format.html { redirect_to :back, notice: 'You can only like/dislike a recipe once.' }
    end
  end
end
#source: Udemy course



  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description)
    end
  end
    def require_same_user
      if current_user != @recipe.user and !current_user.admin?# this statemnet checks if the curent user is not the recipe creator and not the admin 
        respond_to do |format|
          format.html { redirect_to root_path, notice: 'You can only edit your own account' }
        end
    end
  
  
end

#Source:https://www.railstutorial.org/book/updating_and_deleting_users

app/helpers/recipes_helper.rb
module RecipesHelper
    
end

app/views/recipes/_form.html.erb
<%=render 'shared/errors', obj: @recipe%>
  
<div class="row">
  <div class='col-xs-12'>
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Recipe", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of Recipe", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-3">
          <%= link_to "Cancel", recipes_path, class: 'btn btn-primary btn-lg'%>
          </div>
        <div class="col-sm-offset-3 col-sm-3">
          <%= f.submit class: 'btn btn-primary btn-lg'%>
        </div>
      </div>
    <% end %>
  </div>
</div>  

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="recipe-title">
          <%= link_to recipe.title, recipe_path(recipe) %>
           <!-- Like/Dislike Feature -->
            <div class='pull-right like'>
              <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                <i class='glyphicon glyphicon-thumbs-up'></i> &nbsp <%= recipe.thumbs_up_total%>
              <%end%>&nbsp&nbsp
              <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                <i class='glyphicon glyphicon-thumbs-down'></i> &nbsp <%= recipe.thumbs_down_total%>
              <%end%>
            </div>
        </div>
        
        <div class="recipe-body">
          <%= truncate(recipe.description, length: 100) %> 
          <!-- I have used the Truncate method - source: https://github.com/hgmnz/truncate_html-->
          <div class="recipe-meta-details">
            <small>
              Created by: <%= recipe.user.username if recipe.user%>,
              <%= time_ago_in_words(recipe.created_at) %> ago,
              last updated: <%= time_ago_in_words(recipe.updated_at) %> ago
            </small> <!--This code enable us to add the user data to our recipes listing using ruby method: time_ago_in_words 
          to display timing - source:https://www.railstutorial.org/book/user_microposts-->
          
           
          
          </div>
        </div>
        <% if logged_in? && (current_user == recipe.user || current_user.admin?) %><!-- This statemnet checks if the user logged in is the recipe creator and  the admin-->
          <div class="recipe-actions">
            <%= link_to 'Update', edit_recipe_path(recipe), class: "btn btn-xs btn-primary" %> |
            <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
          </div><!-- I have taken @ from (@recipe) on the Links as we are referring to all recipes 
                     not each recipe as it is the case in the show page -->
        <%end%>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<p align="center" id="notice"><%= notice %></p>

<h1 align="center">Editing Recipe</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<p align="center" id="notice"><%= notice %></p>
<h1 align="center">All Recipes</h1>
<div align="center">
  
  <%= will_paginate %> <!-- this will add a display for Pagination -->
  
</div>
<%= render 'recipe', obj: @recipes%>
<div align="center">
  <%= will_paginate %> <!-- this will add a display for Pagination -->
</div>

app/views/recipes/new.html.erb
<h1 align="center">New Recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<p align="center" id="notice"><%= notice %></p>

<h2 align="center">Title:<%= @recipe.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <% if @recipe.user %> <!-- This specific statement will render the recipe if this does not have a user -->
    <ul class="listing">
      <div class="row center">
          <div class="col-md-4 col-md-offset-4">
              <li>Cooked by</li>
              <li><%= link_to gravatar_for(@recipe.user), user_path(@recipe.user) %></li><!-- list User's Gravatar and link it to the use's show page-->
              <li class="recipe-title">
              <%= link_to @recipe.user.username, user_path(@recipe.user) %> </li><!-- list and link Users's name to the use's show page-->
              <li>
                  <small>
                      <%= pluralize(@recipe.user.recipes.count, "recipe") if @recipe.user.recipes %><!--list how many recipes a user has created if he has recipe--> 
                  </small>
              </li>
          </div>
      </div>
    </ul>
  <%end%>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@recipe.description) %>

  <div class="recipe-actions">
    <% if logged_in? && (current_user == @recipe.user || current_user.admin?) %><!-- This statemnet checks if the user logged in is the recipe creator and  the admin-->
      <%= link_to 'Update', edit_recipe_path(@recipe), class: "btn btn-xs btn-primary" %> |
      <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %> |
    <%end%>  
      <%= link_to 'All Recipes', recipes_path, class: "btn btn-xs btn-success" %>
      
<!-- Like/Dislike Feature -->
<div class='pull-right'>
  
  <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
    <i class='glyphicon glyphicon-thumbs-up'></i> &nbsp 
    <%= @recipe.thumbs_up_total%><!--to count how many likes a user has received -->
  <%end%>
  
  &nbsp&nbsp&nbsp
  
  <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
    <i class='glyphicon glyphicon-thumbs-down'></i> &nbsp 
    <%= @recipe.thumbs_down_total%><!--to count how many Dilikes a user has received -->
  <%end%>
  #<!-- Source: Udemy course-->

</div>

  </div>
</div>